---A
--1
SELECT CAUTHU.MACT, CAUTHU.HOTEN, CAUTHU.SO, CAUTHU.VITRI, CAUTHU.NGAYSINH, CAUTHU.DIACHI
FROM CAUTHU;
--2
SELECT * FROM CAUTHU
WHERE CAUTHU.VITRI = N'Tiền vệ' AND CAUTHU.SO = 7;
--3
SELECT TENHLV, NGAYSINH, DIACHI, DIENTHOAI FROM HUANLUYENVIEN;
--4
SELECT * FROM CAUTHU
INNER JOIN QUOCGIA ON CAUTHU.MAQG = QUOCGIA.MAQG
INNER JOIN CAULACBO ON CAUTHU.MACLB = CAULACBO.MACLB
WHERE QUOCGIA.TENQG = N'Việt Nam'
AND CAULACBO.TENCLB = N'Becamex Bình Dương';
--5
SELECT CAUTHU.MACT, CAUTHU.HOTEN, CAUTHU.NGAYSINH, CAUTHU.DIACHI, CAUTHU.VITRI
FROM CAUTHU 
INNER JOIN QUOCGIA ON CAUTHU.MAQG = QUOCGIA.MAQG
INNER JOIN CAULACBO ON CAUTHU.MACLB = CAULACBO.MACLB
WHERE CAULACBO.TENCLB = N'SHB Đà Nẵng';
--6
SELECT * FROM CAUTHU
INNER JOIN CAULACBO ON CAUTHU.MACLB = CAULACBO.MACLB
INNER JOIN SANVD ON CAULACBO.MASAN = SANVD.MASAN
WHERE SANVD.TENSAN = N'Long An';
--7
SELECT TRANDAU.MATRAN, TRANDAU.NGAYTD, SANVD.TENSAN, CB1.TENCLB, CB2.TENCLB, TRANDAU.KETQUA
FROM TRANDAU
INNER JOIN SANVD ON TRANDAU.MASAN = SANVD.MASAN
INNER JOIN CAULACBO CB1 ON TRANDAU.MACLB1 = CB1.MACLB
INNER JOIN CAULACBO CB2 ON TRANDAU.MACLB2 = CB2.MACLB
WHERE TRANDAU.VONG = 2 AND TRANDAU.NAM = 2009;
--8
SELECT HUANLUYENVIEN.MAHLV, HUANLUYENVIEN.TENHLV, HUANLUYENVIEN.NGAYSINH, HUANLUYENVIEN.DIACHI, HLV_CLB.VAITRO, CAULACBO.TENCLB
FROM HUANLUYENVIEN
INNER JOIN HLV_CLB ON HUANLUYENVIEN.MAHLV = HLV_CLB.MAHLV
INNER JOIN CAULACBO ON HLV_CLB.MACLB = CAULACBO.MACLB
INNER JOIN QUOCGIA ON HUANLUYENVIEN.MAQG = QUOCGIA.MAQG
WHERE QUOCGIA.TENQG = N'Việt Nam';
--9
SELECT TOP 3 CAULACBO.TENCLB FROM CAULACBO
INNER JOIN BANGXH ON CAULACBO.MACLB = BANGXH.MACLB
WHERE VONG = 3 AND NAM = 2009
ORDER BY BANGXH.HANG ASC;
--10
SELECT HUANLUYENVIEN.MAHLV, HUANLUYENVIEN.TENHLV, HUANLUYENVIEN.NGAYSINH, HUANLUYENVIEN.DIACHI, HLV_CLB.VAITRO, CAULACBO.TENCLB
FROM HUANLUYENVIEN
INNER JOIN HLV_CLB ON HUANLUYENVIEN.MAHLV = HLV_CLB.MAHLV
INNER JOIN CAULACBO ON HLV_CLB.MACLB = CAULACBO.MACLB
INNER JOIN TINH ON CAULACBO.MATINH = TINH.MATINH
WHERE TINH.TENTINH = N'Bình Dương';

----B

--1
SELECT CAULACBO.TENCLB, COUNT(MACT) AS SOCT
FROM CAULACBO 
INNER JOIN CAUTHU ON CAULACBO.MACLB = CAUTHU.MACLB
GROUP BY CAULACBO.TENCLB;

--2
SELECT CAULACBO.TENCLB, COUNT(MACT) AS SOCT
FROM CAULACBO
INNER JOIN CAUTHU ON CAULACBO.MACLB = CAUTHU.MACLB
INNER JOIN QUOCGIA ON CAUTHU.MAQG = QUOCGIA.MAQG
WHERE QUOCGIA.TENQG != N'Việt Nam'
GROUP BY CAULACBO.TENCLB;

--3
SELECT CAULACBO.MACLB, CAULACBO.TENCLB, SANVD.TENSAN, SANVD.DIACHI, COUNT(MACT)
FROM CAULACBO
INNER JOIN SANVD ON CAULACBO.MASAN = SANVD.MASAN
INNER JOIN CAUTHU ON CAULACBO.MACLB = CAUTHU.MACLB
INNER JOIN QUOCGIA ON CAUTHU.MAQG = QUOCGIA.MAQG
WHERE QUOCGIA.TENQG != N'Việt Nam'
GROUP BY CAULACBO.MACLB, CAULACBO.TENCLB,CAULACBO.TENCLB, SANVD.TENSAN, SANVD.DIACHI
HAVING COUNT(MACT) > 2;

--4
SELECT TINH.TENTINH, COUNT(MACT) AS SOCT
FROM TINH 
INNER JOIN CAULACBO ON CAULACBO.MATINH = TINH.MATINH
INNER JOIN CAUTHU ON CAUTHU.MACLB = CAULACBO.MACLB
WHERE CAUTHU.VITRI = N'Tiền đạo'
GROUP BY TINH.TENTINH;

--5
SELECT TOP 1 CAULACBO.TENCLB, TINH.TENTINH
FROM CAULACBO
INNER JOIN TINH ON TINH.MATINH = CAULACBO.MATINH
INNER JOIN BANGXH ON BANGXH.MACLB = CAULACBO.MACLB
WHERE BANGXH.VONG = 3 AND BANGXH.NAM = 2009
ORDER BY BANGXH.HANG ASC;

---C
--1
SELECT HUANLUYENVIEN.TENHLV FROM HUANLUYENVIEN
INNER JOIN HLV_CLB ON HUANLUYENVIEN.MAHLV = HLV_CLB.MAHLV
WHERE HUANLUYENVIEN.DIENTHOAI IS NULL;

--2
SELECT * FROM HUANLUYENVIEN
LEFT JOIN HLV_CLB ON HUANLUYENVIEN.MAHLV = HLV_CLB.MAHLV
INNER JOIN QUOCGIA ON HUANLUYENVIEN.MAQG = QUOCGIA.MAQG
WHERE QUOCGIA.TENQG = N'Việt Nam'
AND HLV_CLB.MAHLV IS NULL;

--3
SELECT * FROM CAUTHU
INNER JOIN CAULACBO ON CAUTHU.MACLB = CAULACBO.MACLB
INNER JOIN BANGXH ON BANGXH.MACLB = CAULACBO.MACLB
WHERE VONG = 3 AND NAM = 2009
AND (BANGXH.HANG > 6 OR BANGXH.HANG < 3);

--4
SELECT TRANDAU.NGAYTD, SANVD.TENSAN, CB1.TENCLB, CB2.TENCLB, TRANDAU.KETQUA
FROM TRANDAU
INNER JOIN CAULACBO CB1 ON CB1.MACLB = TRANDAU.MACLB1
INNER JOIN CAULACBO CB2 ON CB2.MACLB = TRANDAU.MACLB2
INNER JOIN BANGXH XH1 ON XH1.MACLB = TRANDAU.MACLB1
INNER JOIN BANGXH XH2 ON XH2.MACLB = TRANDAU.MACLB2
INNER JOIN SANVD ON TRANDAU.MASAN = SANVD.MASAN
WHERE (XH1.HANG = 1 AND XH1.VONG = 3 AND XH1.NAM = 2009)
	OR (XH2.HANG = 1 AND XH2.VONG = 3 AND XH2.NAM = 2009);