--A
SELECT KHACHHANG.MAKH, KHACHHANG.HOTEN, KHACHHANG.DCHI, KHACHHANG.SODT
from KHACHHANG
inner join HOADON on KHACHHANG.MAKH = HOADON.MAKH
inner join CTHOADON on CTHOADON.SOHD = HOADON.SOHD
group by KHACHHANG.MAKH, KHACHHANG.HOTEN, KHACHHANG.DCHI, KHACHHANG.SODT
having sum(CTHOADON.SL) >= 3;
--B
SELECT HOADON.SOHD, HOADON.NGAYHD, KHACHHANG.HOTEN, KHACHHANG.DCHI, CTHOADON.SL * SANPHAM.DONGIA as [Tổng tiền]
FROM HOADON
INNER JOIN KHACHHANG ON HOADON.MAKH = KHACHHANG.MAKH
INNER JOIN CTHOADON ON CTHOADON.SOHD = HOADON.SOHD
INNER JOIN SANPHAM ON CTHOADON.MASP = SANPHAM.MASP
WHERE DATEDIFF(YEAR, NGSINH, GETDATE()) > 35;
--C
SELECT TOP 1 SANPHAM.MASP, SANPHAM.TENSP, SANPHAM.DONGIA, SANPHAM.NUOCSX
FROM SANPHAM
INNER JOIN CTHOADON ON SANPHAM.MASP = CTHOADON.MASP
INNER JOIN HOADON ON HOADON.SOHD = CTHOADON.SOHD
WHERE YEAR(NGAYHD) = 2017
GROUP BY SANPHAM.MASP, SANPHAM.TENSP, SANPHAM.DONGIA, SANPHAM.NUOCSX
ORDER BY SUM(SL) DESC;
--D
select KHACHHANG.MAKH, KHACHHANG.HOTEN, KHACHHANG.DCHI, KHACHHANG.SODT, KHACHHANG.NGSINH
from KHACHHANG
inner join HOADON on HOADON.MAKH = KHACHHANG.MAKH
inner join CTHOADON on CTHOADON.SOHD = HOADON.SOHD
inner join SANPHAM on SANPHAM.MASP = CTHOADON.MASP
where SANPHAM.TENSP = N'Bình nước'
group by KHACHHANG.MAKH, KHACHHANG.HOTEN, KHACHHANG.DCHI, KHACHHANG.SODT, KHACHHANG.NGSINH
having sum(SL) > 1;
--E
select KHACHHANG.MAKH, KHACHHANG.HOTEN, KHACHHANG.DCHI, KHACHHANG.SODT 
from KHACHHANG
inner join HOADON on HOADON.MAKH = KHACHHANG.MAKH
inner join CTHOADON on CTHOADON.SOHD = HOADON.SOHD
inner join SANPHAM on SANPHAM.MASP = CTHOADON.MASP
where SANPHAM.NUOCSX = N'MỸ'
group by KHACHHANG.MAKH, KHACHHANG.HOTEN, KHACHHANG.DCHI, KHACHHANG.SODT 
having count(distinct cthoadon.MASP) = (select count(MASP) from SANPHAM where NUOCSX = N'MỸ');

--F
SELECT SANPHAM.MASP, SANPHAM.TENSP, SANPHAM.NUOCSX, SANPHAM.DONGIA 
from SANPHAM
where not SANPHAM.MASP in (
SELECT SANPHAM.MASP
from SANPHAM
inner join CTHOADON on CTHOADON.MASP = SANPHAM.MASP
inner join HOADON on HOADON.SOHD = CTHOADON.SOHD
where year(NGAYHD) = 2017
)
select * from HOADON;
insert into HOADON
values 
(81375, '11/15/2017', 'HDG.001')

insert into CTHOADON
values
(81375, 'USA.REMOTE', 100)

select * from CTHOADON;
select * from HOADON;
--G
select KHACHHANG.MAKH, KHACHHANG.HOTEN, KHACHHANG.DCHI, count(HOADON.SOHD) as [Tổng số lần mua], sum(CTHOADON.SL*SANPHAM.DONGIA) as [Tổng tiền hóa đơn mua]
from KHACHHANG
inner join HOADON on HOADON.MAKH = KHACHHANG.MAKH
inner join CTHOADON on CTHOADON.SOHD = HOADON.SOHD
inner join SANPHAM on SANPHAM.MASP = CTHOADON.MASP
where year(NGAYHD) = 2017
group by KHACHHANG.MAKH, KHACHHANG.HOTEN, KHACHHANG.DCHI
having count(HOADON.SOHD) > 4
and sum(CTHOADON.SL*SANPHAM.DONGIA) > 10000000;
--H
