---A
--1,
SELECT TRANDAU.NGAYTD,  CB1.TENCLB TENCLB1, CB2.TENCLB TENCLB2, TRANDAU.KETQUA
FROM TRANDAU
INNER JOIN CAULACBO CB1 ON TRANDAU.MACLB1 = CB1.MACLB
INNER JOIN CAULACBO CB2 ON TRANDAU.MACLB2 = CB2.MACLB
WHERE (SELECT MONTH(TRANDAU.NGAYTD)) = 3
AND 
(((SELECT SUBSTRING(TRANDAU.KETQUA, 3, 1)) = 0
AND CB1.MASAN = TRANDAU.MASAN )
OR ((SELECT SUBSTRING(TRANDAU.KETQUA, 1, 1)) = 0
AND CB2.MASAN = TRANDAU.MASAN ));
--2,
SELECT MACT, HOTEN, NGAYSINH FROM CAUTHU
WHERE HOTEN LIKE N'% Công %';
--3,
SELECT MACT, HOTEN, NGAYSINH FROM CAUTHU
WHERE NOT HOTEN LIKE N'Nguyễn %';
--4,
SELECT MAHLV, TENHLV, NGAYSINH, DIACHI
FROM HUANLUYENVIEN
WHERE (SELECT YEAR(NGAYSINH)) <= (SELECT YEAR(GETDATE()) - 35) 
AND (SELECT YEAR(NGAYSINH)) >= (SELECT YEAR(GETDATE()) - 40)
AND HUANLUYENVIEN.MAQG = (SELECT MAQG FROM QUOCGIA
						  WHERE TENQG = N'Việt Nam');
--5,
SELECT CAULACBO.TENCLB FROM CAULACBO
INNER JOIN HLV_CLB ON CAULACBO.MACLB = HLV_CLB.MACLB
INNER JOIN HUANLUYENVIEN ON HLV_CLB.MAHLV = HUANLUYENVIEN.MAHLV
WHERE (SELECT DAY(HUANLUYENVIEN.NGAYSINH)) = 20
AND (SELECT MONTH(HUANLUYENVIEN.NGAYSINH)) = 8
AND (SELECT DAY(HUANLUYENVIEN.NGAYSINH)) = 2019
AND HLV_CLB.VAITRO = N'HLV Chính';
--6
SELECT TOP 1 CAULACBO.TENCLB, TINH.TENTINH
FROM CAULACBO
INNER JOIN TINH ON CAULACBO.MATINH = TINH.MATINH
INNER JOIN BANGXH ON BANGXH.MACLB = CAULACBO.MACLB
WHERE BANGXH.NAM = 2009 AND BANGXH.VONG = 3
ORDER BY (SUBSTRING(BANGXH.HIEUSO, 1, 1)) DESC;
---B
--1
SELECT CAULACBO.MACLB, CAULACBO.TENCLB, SANVD.TENSAN, SANVD.DIACHI, COUNT(MACT) SOCT
FROM CAULACBO
INNER JOIN SANVD ON CAULACBO.MASAN = SANVD.MASAN
INNER JOIN CAUTHU ON CAULACBO.MACLB = CAUTHU.MACLB
WHERE NOT CAUTHU.MAQG = (SELECT MAQG FROM QUOCGIA
						  WHERE TENQG = N'Việt Nam')
						  GROUP BY CAULACBO.MACLB, CAULACBO.TENCLB, SANVD.TENSAN, SANVD.DIACHI
HAVING COUNT(MACT) > 2;
--2
SELECT TOP 1 CAULACBO.TENCLB, TINH.TENTINH
FROM CAULACBO 
INNER JOIN TINH ON CAULACBO.MATINH = TINH.MATINH
INNER JOIN BANGXH ON CAULACBO.MACLB = BANGXH.MACLB
WHERE BANGXH.VONG IN (SELECT TOP 1 BANGXH.VONG FROM BANGXH
						ORDER BY BANGXH.VONG DESC)
AND BANGXH.NAM = 2009
ORDER BY (CAST(SUBSTRING(BANGXH.HIEUSO, 1, 1) AS INT) - CAST(SUBSTRING(BANGXH.HIEUSO, 3, 1) AS INT)) DESC;
--3
SELECT TRANDAU.NGAYTD, SANVD.TENSAN, CB1.TENCLB CLB1, CB2.TENCLB CLB2, TRANDAU.KETQUA
FROM TRANDAU
INNER JOIN CAULACBO CB1 ON TRANDAU.MACLB1 = CB1.MACLB
INNER JOIN CAULACBO CB2 ON TRANDAU.MACLB2 = CB2.MACLB
INNER JOIN SANVD ON SANVD.MASAN = TRANDAU.MASAN
WHERE CB1.MACLB = (SELECT TOP 1 MACLB FROM BANGXH
					WHERE BANGXH.VONG = 3 AND BANGXH.NAM = 2009
					ORDER BY HANG ASC)
OR CB2.MACLB = (SELECT TOP 1 MACLB FROM BANGXH
					WHERE BANGXH.VONG = 3 AND BANGXH.NAM = 2009
					ORDER BY HANG ASC);
--4
SELECT DISTINCT MACLB, TENCLB
FROM CAULACBO C 
WHERE NOT EXISTS (SELECT MACLB FROM CAULACBO C1 WHERE C.MACLB <> C1.MACLB
				  EXCEPT ((SELECT MACLB1 FROM TRANDAU TD1 WHERE C.MACLB = TD1.MACLB2)
					UNION (SELECT MACLB2 FROM TRANDAU TD2 WHERE C.MACLB = TD2.MACLB2))
				  );
--5
SELECT DISTINCT MACLB, TENCLB
FROM TRANDAU TD1 
INNER JOIN CAULACBO C ON TD1.MACLB1 = C.MACLB
WHERE NOT EXISTS (SELECT MACLB FROM CAULACBO CLB1
				  EXCEPT ((SELECT MACLB2 FROM TRANDAU TD2 WHERE TD1.MACLB1 = TD2.MACLB1)
				    UNION (SELECT MACLB FROM CAULACBO CLB2 WHERE MACLB = TD1.MACLB1))
				  );
---C
--1
ALTER TABLE CAUTHU
ADD CONSTRAINT CHK_POS CHECK(VITRI IN (N'Thủ môn', N'Tiền đạo', N'Tiền vệ', N'Trung vệ', N'Hậu vệ'));
GO
--2
ALTER TABLE HLV_CLB
ADD CONSTRAINT CHK_FUNC CHECK(VAITRO IN(N'HLV Chính', N'HLV phụ', N'HLV thể lực', N'HLV thủ môn'));
GO
--3
ALTER TABLE CAUTHU
ADD CONSTRAINT CHK_AGE CHECK(YEAR(GETDATE()) - YEAR(NGAYSINH) >= 18);
GO
--4
ALTER TABLE TRANDAU
ADD CONSTRAINT CHK_RES CHECK(KETQUA LIKE '%-%');
GO

---D
-- 1
CREATE VIEW V1 AS
SELECT MACT, HOTEN, NGAYSINH, DIACHI, VITRI
FROM CAUTHU 
JOIN CAULACBO ON CAUTHU.MACLB = CAULACBO.MACLB
JOIN QUOCGIA ON CAUTHU.MAQG = QUOCGIA.MAQG
WHERE TENCLB = N'SHB Đà Nẵng' AND TENQG = N'Bra-xin';
SELECT * FROM V1;

-- 2
CREATE VIEW V2 AS
SELECT MATRAN, NGAYTD, SVD.TENSAN, CLB1.TENCLB AS [TENCLB1], CLB2.TENCLB AS [TENCLB2], KETQUA
FROM TRANDAU td
JOIN SANVD svd ON svd.MASAN = td.MASAN
JOIN CAULACBO clb1 ON clb1.MACLB = td.MACLB1
JOIN CAULACBO clb2 ON clb2.MACLB = td.MACLB2
WHERE VONG = 3 AND NAM = 2009;
SELECT * FROM V2;

-- 3
CREATE VIEW V3 AS
SELECT hlv.MAHLV, TENHLV, NGAYSINH, DIACHI, VAITRO, TENCLB
FROM HUANLUYENVIEN hlv
JOIN HLV_CLB ON hlv.MAHLV = HLV_CLB.MAHLV
JOIN CAULACBO clb ON HLV_CLB.MACLB = clb.MACLB
JOIN QUOCGIA qg ON hlv.MAQG = qg.MAQG
WHERE TENQG = N'Việt Nam';
SELECT * FROM V3;

-- 4
CREATE VIEW V4 AS
SELECT clb.MACLB, TENCLB, TENSAN, svd.DIACHI, COUNT(MACT) AS [Số lượng cầu thủ nước ngoài]
FROM CAULACBO clb
JOIN SANVD svd ON clb.MASAN = svd.MASAN
JOIN CAUTHU ct ON clb.MACLB = ct.MACLB
JOIN QUOCGIA qg ON ct.MAQG = qg.MAQG
WHERE TENQG <> N'Việt Nam'
GROUP BY clb.MACLB, TENCLB, TENSAN, svd.DIACHI
HAVING COUNT(MACT) > 2;
SELECT * FROM V4;

-- 5
CREATE VIEW V5 AS
SELECT TENTINH, COUNT(MACT) AS [Số lượng cầu thủ đang thi đấu ở vị trí tiền đạo]
FROM TINH
JOIN CAULACBO clb ON TINH.MATINH = clb.MATINH
JOIN CAUTHU ct ON clb.MACLB = ct.MACLB
WHERE VITRI = N'Tiền đạo'
GROUP BY TENTINH;
SELECT * FROM V5;

-- 6
CREATE VIEW V6 AS
SELECT TOP 1 TENCLB, TENTINH
FROM CAULACBO clb
JOIN TINH ON clb.MATINH = TINH.MATINH
JOIN BANGXH bxh ON bxh.MACLB = clb.MACLB
WHERE VONG = 3 AND NAM = 2009;
SELECT * FROM V6;

-- 7
CREATE VIEW V7 AS
SELECT TENHLV
FROM HUANLUYENVIEN hlv
JOIN HLV_CLB ON hlv.MAHLV = HLV_CLB.MAHLV
WHERE HLV_CLB.VAITRO IS NOT NULL AND hlv.DIENTHOAI IS NULL;
SELECT * FROM V7;

-- 8
CREATE VIEW V8 AS
SELECT TENHLV
FROM HUANLUYENVIEN hlv
JOIN HLV_CLB ON hlv.MAHLV = HLV_CLB.MAHLV
JOIN QUOCGIA qg ON hlv.MAQG = qg.MAQG
WHERE qg.TENQG = N'Việt Nam' AND HLV_CLB.MACLB IS NULL AND HLV_CLB.VAITRO IS NULL;
SELECT * FROM V8;

-- 9
CREATE VIEW V9 AS
SELECT MACLB1, MACLB2, NAM, VONG, 
       SUBSTRING(KETQUA, 1, CHARINDEX('-', KETQUA, 1) - 1) AS [Số bàn thắng của CLB1],
       SUBSTRING(KETQUA, CHARINDEX('-', KETQUA, 1) + 1, LEN(KETQUA)) AS [Số bàn thua của CLB1]
FROM TRANDAU;
SELECT * FROM V9;

-- 10
CREATE VIEW V10 AS
SELECT MACLB1 AS [MA CLB], NAM, VONG,  
       SUBSTRING(KETQUA, 1, CHARINDEX('-', KETQUA, 1) - 1) AS [SOBANTHANG], 
       SUBSTRING(KETQUA, CHARINDEX('-', KETQUA, 1) + 1, LEN(KETQUA)) AS [SOBANTHUA]
FROM TRANDAU;
SELECT * FROM V10;

-- 11
CREATE VIEW V11 AS
SELECT MACLB2 AS [MA CLB], NAM, VONG,  
       SUBSTRING(KETQUA, CHARINDEX('-', KETQUA, 1) + 1, LEN(KETQUA)) AS [SOBANTHANG],
       SUBSTRING(KETQUA, 1, CHARINDEX('-', KETQUA, 1) - 1) AS [SOBANTHUA]
FROM TRANDAU;
SELECT * FROM V11;

-- 12
CREATE VIEW v12 AS
SELECT NGAYTD, TENSAN, clb1.TENCLB AS [TENCLB1], clb2.TENCLB AS [TENCLB2], KETQUA
FROM TRANDAU td
INNER JOIN SANVD svd ON td.MASAN = svd.MASAN
INNER JOIN CAULACBO clb1 ON td.MACLB1 = clb1.MACLB
INNER JOIN CAULACBO clb2 ON td.MACLB2 = clb2.MACLB
WHERE td.MACLB1 = (SELECT TOP 1 MACLB FROM BANGXH
                   WHERE VONG = 3 AND NAM = 2009
                   ORDER BY DIEM DESC)
   OR td.MACLB2 = (SELECT TOP 1 MACLB FROM BANGXH
                   WHERE VONG = 3 AND NAM = 2009
                   ORDER BY DIEM DESC);
SELECT * FROM v12;

-- 13
CREATE VIEW v13 AS
SELECT NGAYTD, TENSAN, clb1.TENCLB AS [TENCLB1], clb2.TENCLB AS [TENCLB2], KETQUA
FROM TRANDAU td
INNER JOIN SANVD svd ON td.MASAN = svd.MASAN
INNER JOIN CAULACBO clb1 ON td.MACLB1 = clb1.MACLB
INNER JOIN CAULACBO clb2 ON td.MACLB2 = clb2.MACLB
WHERE td.MACLB1 = (SELECT TOP 1 MACLB FROM BANGXH
                   WHERE VONG = 3 AND NAM = 2009
                   ORDER BY DIEM ASC)
   OR td.MACLB2 = (SELECT TOP 1 MACLB FROM BANGXH
                   WHERE VONG = 3 AND NAM = 2009
                   ORDER BY DIEM ASC);

SELECT * FROM v13;





       